### ISSUE TITLE
Add faucet feature

### ISSUE THREAD

**Issue by mario4tier** [sui-base/sui-base#15]
Investigate. If implemented, should be configurable through sui-base.yaml:

https://forums.sui.io/t/running-local-gas-faucet-url/25773/4

**Comment by FrankC01** [comment]
Observation notes:
- `sui-faucet --write-ahead-log /tmp/faucet.wal` consumes coins from the addresses coins, it doesn't mint new gas
- `sui-test-validator` does not have a client.yaml notion although their are commends in the code with a TODO to support that
